// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzrQ2PknHoZykjCZVNOfBfwyhEEzNr_L4',
    appId: '1:590228057164:web:02d13130a3f248269b58e9',
    messagingSenderId: '590228057164',
    projectId: 'mocker-ai-52505',
    authDomain: 'mocker-ai-52505.firebaseapp.com',
    storageBucket: 'mocker-ai-52505.firebasestorage.app',
    measurementId: 'G-1RYPCZK1NL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCceLQ3f14qfogjCerW0koVfAnUmKUX5i8',
    appId: '1:590228057164:android:c1f97f83cc60a7d09b58e9',
    messagingSenderId: '590228057164',
    projectId: 'mocker-ai-52505',
    storageBucket: 'mocker-ai-52505.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtW_Ozc_UeYw8AIZ7IxDcts7cOv3y6bFs',
    appId: '1:590228057164:ios:67dfd11e758329b39b58e9',
    messagingSenderId: '590228057164',
    projectId: 'mocker-ai-52505',
    storageBucket: 'mocker-ai-52505.firebasestorage.app',
    iosBundleId: 'com.example.mockerAi',
  );
}
